version: '3'
services:
  tracing:
    image: 'jaegertracing/all-in-one:1.25'
    hostname: 'jaeger'
    container_name: 'jaeger'
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '14250:14250'
  server:
    image: '$package$/server:1.0'
    hostname: 'grpc-server'
    container_name: 'grpc-server'
    depends_on:
      - tracing
    ports:
      - '8080:8080'
      - '8081:8081'
  client:
    image: '$package$/client:1.0'
    hostname: 'grpc-client'
    container_name: 'grpc-client'
    depends_on:
      - tracing
      - server
    ports:
      - '8082:8082'